### ISSUE TITLE
Shadow Transformer Usage

### ISSUE THREAD

**Issue by stefan-kolb** [TheBoegl/shadow-log4j-transformer#2]
Hi, 

we tried to replace our transformer patch with your plugin, see https://github.com/JabRef/jabref/commit/565e19ebfc3cfde3b927b56b637320a66d722d0a
However, we get the typical errors again.
`ERROR StatusLogger Unrecognized format specifier [d]`.
Are we doing something wrong? Maybe you can help us out!
Thanks, Stefan

**Comment by TheBoegl** [comment]
Hi Stefan,

I'll try to look into this at the end of this week.

Best regards,
Sebastian

**Comment by TheBoegl** [comment]
If you use this plugin [as library](https://github.com/TheBoegl/shadow-log4j-transformer#usage-as-library) it seems to work.
Can you confirm this?

**Comment by stefan-kolb** [comment]
Yes, looks like this is working. What could be the problem here then?
I'd rather use it as a plugin as it keeps the build file clean.

**Comment by TheBoegl** [comment]
Please have a look at the latest version `2.1.1` which should fix this issue.

**Comment by stefan-kolb** [comment]
Looks like it works 👍 
Thank you for your help!
Another quick suggestion: I'd move https://github.com/TheBoegl/shadow-log4j-transformer#using-the-gradle-plugin-dsl to the very top in the README as it is the easiest and cleanest solution to use the transformer?!

**Comment by TheBoegl** [comment]
You're welcome!
[John Engelman](/johnrengelman) noted [correctly](https://github.com/johnrengelman/shadow/issues/207#issuecomment-271642247) that a gradle plugin is overkill to provide just one transformer class. Hence, it is mentioned in the README for the sake of completeness only.
