### ISSUE TITLE
Dependency error on log4j and jengelman.gradle.plugins.shadow2

### ISSUE THREAD

**Issue by Siedlerchr** [TheBoegl/shadow-log4j-transformer#3]
Hi,

we are getting the following gradle build error on some CI systems:

```
Could not find any matches for org.apache.logging.log4j:log4j-core:2.+ as no versions of org.apache.logging.log4j:log4j-core are available.
 Searched in the following locations: 
https://plugins.gradle.org/m2/org/apache/logging/log4j/log4j-core/maven-metadata.xml
Required by:
project : > gradle.plugin.de.sebastianboegl.gradle.plugins:shadow-log4j-transformer:2.1.1

> Could not find any matches for com.github.jengelman.gradle.plugins:shadow:2.+ as no versions of com.github.jengelman.gradle.plugins:shadow are available.
Searched in the following locations:
https://plugins.gradle.org/m2/com/github/jengelman/gradle/plugins/shadow/maven-metadata.xml Required by: project : 
> gradle.plugin.de.sebastianboegl.gradle.plugins:shadow-log4j-transformer:2.1.1
```

**Comment by TheBoegl** [comment]
Try to use this _plugin_ as [library](https://github.com/TheBoegl/shadow-log4j-transformer#usage-as-library) or please provide more information or, even better, a short sample project.

**Comment by Siedlerchr** [comment]
Hi,
the above mentioned error occur from using lgtm.com analysis, here is a [sample log file with the error](https://lgtm.com/projects/g/JabRef/jabref/logs/rev/pr-5e3efa25b9be2fdcc3d1f9781c435d9a92c1c17b).

we are using your plugin in [Jabref](https://github.com/JabRef/jabref)  in our build.gradle: 
https://github.com/JabRef/jabref/blob/master/build.gradle in the following way:

```
plugins {
    id 'com.github.johnrengelman.shadow' version '2.0.1'
    id "de.sebastianboegl.shadow.transformer.log4j" version "2.1.1"
}
shadowJar {
    classifier 'fat'
}

dependencies{
    compile 'commons-logging:commons-logging:1.2'
    compile 'org.apache.logging.log4j:log4j-jcl:2.9.1'
    compile 'org.apache.logging.log4j:log4j-api:2.9.1'
    compile 'org.apache.logging.log4j:log4j-core:2.9.1'
}
```

**Comment by TheBoegl** [comment]
Does this error only occur in lgtm or somewhere else?
Except from some failing tests the JabRef master branch seems to run OK here...

**Comment by Siedlerchr** [comment]
It is only failing on LGTM, I guess it's due to some caching. Travis CI caches dependencies. Our build script first check if the dependencies are locally available, for

**Comment by Siedlerchr** [comment]
For example, it checks, if they are in a local maven repository available

**Comment by TheBoegl** [comment]
The gradle plugins portal seems to fail to [retrieve dynamic versions](https://discuss.gradle.org/t/why-the-gradle-central-plugin-repository-does-not-support-dynamic-plugin-versions/11788).
As mentioned above, try to apply this as library.  Add _jcenter_ to the buildscript libraries which handles the dynamic versions correctly:
```
buildscript {
    repositories {
        mavenLocal()
        jcenter()
    }
    dependencies {
        classpath 'de.sebastianboegl.gradle.plugins:shadow-log4j-transformer:2.1.1'
    }
}
```
