### ISSUE TITLE
Update Gradle

### ISSUE THREAD

**Issue by daberkow** [TheBoegl/shadow-log4j-transformer#8]
The readme mentions using "https://plugins.gradle.org/m2/" but there the latest version seems to be 2.1.1

**Comment by TheBoegl** [comment]
Is there any problem or issue with the used Gradle version for you?

**Comment by daberkow** [comment]
If you browse to the folder, it doesnt seem to have the latest versions. https://plugins.gradle.org/m2/com/github/jengelman/gradle/plugins/shadow/

**Comment by TheBoegl** [comment]
Are you referring to the part in the [Readme](/TheBoegl/shadow-log4j-transformer/blob/master/README.md) stating `At the time of writing, the latest shadow plugin version was 2.0.2.` if so please read further in this document and use this [as library ](/TheBoegl/shadow-log4j-transformer/blob/master/README.md#usage-as-library) with the shadow plugin of your liking.

**Comment by daberkow** [comment]
My worry is that the gradle library isnt getting the newest versions uploaded. It seems the last version added there was 2.0.4 :fearful:

**Comment by TheBoegl** [comment]
It is up to the shadow plugin user, as for every other gradle plugin, to check for the latest plugins and apply them, if they need the features of the update.

**Comment by TheBoegl** [comment]
closing this on no response
