### ISSUE TITLE
Breaking change with Shadow 4.0.1

### ISSUE THREAD

**Issue by meydominic** [TheBoegl/shadow-log4j-transformer#9]
John released version 4.0.1 of his shadow library.

There is a breaking change in it so that your library is not working any more.

Changelog: http://imperceptiblethoughts.com/shadow/#change_log
Github-Issue: https://github.com/johnrengelman/shadow/issues/404

Maybe you can update your library to work with latest version again?

Thanks :)

**Comment by TheBoegl** [comment]
The Log4jTransformer ist part of the shadow plugin since version 4.0.0 if I've read the changelog correctly.

**Comment by meydominic** [comment]
Yeah,
you're right. My fault 😆 
I changed it to the included transformer and it's working now. Thanks :)

Entry of changelog:
_Add Log4j2PluginsCacheFileTransformer to process Log4j DAT files during merge._
